### padnsa consist of the tw odata structure called as serires and dataframe --- 1. serires -- it is an one dimensional aarray like obj ---2.----  datafram ---- a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
! pip install pandas

Requirement already satisfied: pandas in d:\mldlnlp\myenv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\mldlnlp\myenv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\mldlnlp\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\mldlnlp\myenv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\mldlnlp\myenv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\mldlnlp\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
## series in pandas
data = [1,2,3,4,5]

series  = pd.Series(data)
print(series) # it provides elemnts in the list along woth ther indexes

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# Creating the sseries from the dictonaries
data = [10, 20 , 30]
index = ['a','b','c']

pd.Series(data , index = index)

a    10
b    20
c    30
dtype: int64

In [6]:
# data frma 2 dimensional heterrogenous data 


#  first  we will create the dictoniers 

data = {

    'nmae' : ['a' , 'b' , 'c'] ,
    'Roll' : [2,3,4 ] ,
    'city ' : ['hyd' , 'delhi' , 'bangalore']
}
df = pd.DataFrame(data)
print(df)

  nmae  Roll      city
0    a     2        hyd
1    b     3      delhi
2    c     4  bangalore

In [7]:
 # creaitng the datafram fromlist of the dictonaries 

data = [

    {' name ' :'krish' , 'age': 23 , 'city' : 'hyd' } ,
    {' name ' : 'ram' , 'age': 25 , 'city' : 'delhi' } ,
    {' name ' : 'raju' , 'age': 22 , 'city' : 'bangalore' }
]

df  = pd.DataFrame(data) 
print(df)

   name   age       city
0  krish   23        hyd
1    ram   25      delhi
2   raju   22  bangalore

In [8]:

df = pd.read_csv('data.csv')
(df.head())

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [9]:
#accessing the particaular data 
df['Value']

0     28.0
1     39.0
2     32.0
3      8.0
4     26.0
5     54.0
6     16.0
7     89.0
8     37.0
9     22.0
10     7.0
11    60.0
12    70.0
13    69.0
14    47.0
15     NaN
16    93.0
17     NaN
18    31.0
19    59.0
20    82.0
21    37.0
22    62.0
23    92.0
24    24.0
25    95.0
26    71.0
27    56.0
28     NaN
29    51.0
30    50.0
31    17.0
32    63.0
33    27.0
34    70.0
35    60.0
36    36.0
37     2.0
38    94.0
39    62.0
40    15.0
41    97.0
42    93.0
43    43.0
44    96.0
45    99.0
46     6.0
47    69.0
48    65.0
49    11.0
Name: Value, dtype: float64

In [10]:
# to acces the particular row index 
df.loc[0] # --0--- indicats the index

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [11]:
# to acces the particular row index 
df.loc[0][1] # --0--- indicats the index

C:\Users\bhoir\AppData\Local\Temp\ipykernel_13240\2151001936.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][1] # --0--- indicats the index

'A'

In [12]:
# accessing particular cell  data
df.at[1,'Category'] # this provide from data at index 1 the value of the category

'B'

In [13]:
# sccesing the specofic element usinfg " iat "
df.iat[2,2] # element at hte second row and second column

np.float64(32.0)

In [14]:
data
df = pd.DataFrame(data)
df

   name   age       city
0  krish   23        hyd
1    ram   25      delhi
2   raju   22  bangalore

In [15]:
# insertinfg the coluumn 
df['sal'] = [10,20,30]

In [16]:
df

   name   age       city  sal
0  krish   23        hyd   10
1    ram   25      delhi   20
2   raju   22  bangalore   30

In [17]:
# deleting the column 
df.drop('sal' , axis = 1)  # axis = 1 indicates column

   name   age       city
0  krish   23        hyd
1    ram   25      delhi
2   raju   22  bangalore

In [18]:
# now ece after we remove teh coluimn it does not updates in the table
df

   name   age       city  sal
0  krish   23        hyd   10
1    ram   25      delhi   20
2   raju   22  bangalore   30

In [19]:
# so to save teh changes we made the use of the function/ parametes 
# knows as   "inplace = True "
df.drop('sal' , axis = 1 , inplace = True)

In [20]:
df

   name   age       city
0  krish   23        hyd
1    ram   25      delhi
2   raju   22  bangalore

In [21]:
# performing addition operation to the values of the age col 
df['age']+1

0    24
1    26
2    23
Name: age, dtype: int64

In [22]:
# droping the row 
df.drop(0 ) # twe can make use "inplace = True" her also

   name   age       city
1    ram   25      delhi
2   raju   22  bangalore

In [23]:
# to get hte stastical analysis we can make use of the 
# " df.describe"
df.describe()

             age
count   3.000000
mean   23.333333
std     1.527525
min    22.000000
25%    22.500000
50%    23.000000
75%    24.000000
max    25.000000

In [24]:
len(df)

3

# data manipulation with Pandas

In [25]:
df = pd.read_csv('data.csv')
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [26]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [27]:
# handling the missing values
df.isnull().any(axis=1 ) # here axis = 1 indicate for every record it willl show hweer ther is the missing value and wherethere is not

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [28]:
df.isnull().sum()  # here it will show the total number of missing values in each column

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [29]:
df_filled = df.fillna(0) # fillna indicates to fill the missing values with the given value here 0
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [30]:
# filling the missing values with the measn of the column
# 3 HERE HWERE EVER the NAN / Null values are present we will replacethat with the "measn" of the sales 
df['Salesfillna'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Salesfillna
0   2023-01-01        A   28.0  Product1  754.0   East   754.000000
1   2023-01-02        B   39.0  Product3  110.0  North   110.000000
2   2023-01-03        C   32.0  Product2  398.0   East   398.000000
3   2023-01-04        B    8.0  Product1  522.0   East   522.000000
4   2023-01-05        B   26.0  Product3  869.0  North   869.000000
5   2023-01-06        B   54.0  Product3  192.0   West   192.000000
6   2023-01-07        A   16.0  Product1  936.0   East   936.000000
7   2023-01-08        C   89.0  Product1  488.0   West   488.000000
8   2023-01-09        C   37.0  Product3  772.0   West   772.000000
9   2023-01-10        A   22.0  Product2  834.0   West   834.000000
10  2023-01-11        B    7.0  Product1  842.0  North   842.000000
11  2023-01-12        B   60.0  Product2    NaN   West   557.130435
12  2023-01-13        A   70.0  Product3  628.0  South   628.000000
13  2023-01-14        A   69.0  Product1  423.0   East   423.000000
14  2023-01-15        A   47.0  Product2  893.0   West   893.000000
15  2023-01-16        C    NaN  Product1  895.0  North   895.000000
16  2023-01-17        C   93.0  Product2  511.0  South   511.000000
17  2023-01-18        C    NaN  Product1  108.0   West   108.000000
18  2023-01-19        A   31.0  Product2  578.0   West   578.000000
19  2023-01-20        A   59.0  Product1  736.0   East   736.000000
20  2023-01-21        C   82.0  Product3  606.0  South   606.000000
21  2023-01-22        C   37.0  Product2  992.0  South   992.000000
22  2023-01-23        B   62.0  Product3  942.0  North   942.000000
23  2023-01-24        C   92.0  Product2  342.0   West   342.000000
24  2023-01-25        A   24.0  Product2  458.0   East   458.000000
25  2023-01-26        C   95.0  Product1  584.0   West   584.000000
26  2023-01-27        C   71.0  Product2  619.0  North   619.000000
27  2023-01-28        C   56.0  Product2  224.0  North   224.000000
28  2023-01-29        B    NaN  Product3  617.0  North   617.000000
29  2023-01-30        C   51.0  Product2  737.0  South   737.000000
30  2023-01-31        B   50.0  Product3  735.0   West   735.000000
31  2023-02-01        A   17.0  Product2  189.0   West   189.000000
32  2023-02-02        B   63.0  Product3  338.0  South   338.000000
33  2023-02-03        C   27.0  Product3    NaN   East   557.130435
34  2023-02-04        C   70.0  Product3  669.0   West   669.000000
35  2023-02-05        B   60.0  Product2    NaN   West   557.130435
36  2023-02-06        C   36.0  Product3  177.0   East   177.000000
37  2023-02-07        C    2.0  Product1    NaN  North   557.130435
38  2023-02-08        C   94.0  Product1  408.0  South   408.000000
39  2023-02-09        A   62.0  Product1  155.0   West   155.000000
40  2023-02-10        B   15.0  Product1  578.0   East   578.000000
41  2023-02-11        C   97.0  Product1  256.0   East   256.000000
42  2023-02-12        A   93.0  Product3  164.0   West   164.000000
43  2023-02-13        A   43.0  Product3  949.0   East   949.000000
44  2023-02-14        A   96.0  Product3  830.0   East   830.000000
45  2023-02-15        B   99.0  Product2  599.0   West   599.000000
46  2023-02-16        B    6.0  Product1  938.0  South   938.000000
47  2023-02-17        B   69.0  Product3  143.0   West   143.000000
48  2023-02-18        C   65.0  Product3  182.0  North   182.000000
49  2023-02-19        C   11.0  Product3  708.0  North   708.000000

In [31]:
# How to vhane an datatype
df.dtypes

Date            object
Category        object
Value          float64
Product         object
Sales          float64
Region          object
Salesfillna    float64
dtype: object

In [32]:
# suppose wewant t ochange the floar64 of the sales into the number or we  can say as an "int"


# --1--- # rennaimg the column 

df = df.rename(columns = {'Date ' : 'Sales Date'})
df.head()

         Date Category  Value   Product  Sales Region  Salesfillna
0  2023-01-01        A   28.0  Product1  754.0   East        754.0
1  2023-01-02        B   39.0  Product3  110.0  North        110.0
2  2023-01-03        C   32.0  Product2  398.0   East        398.0
3  2023-01-04        B    8.0  Product1  522.0   East        522.0
4  2023-01-05        B   26.0  Product3  869.0  North        869.0

In [33]:
df['value_new']  = df['Value'].fillna(df["Value"].mean()).astype(int)
df.head() # -- here inside ---astype() ---we providethe parameter as teh the goal the value type tha we that we want

         Date Category  Value   Product  Sales Region  Salesfillna  value_new
0  2023-01-01        A   28.0  Product1  754.0   East        754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North        110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East        398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East        522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North        869.0         26

In [34]:
# aplllying the operations to any of the functions 
df['NewVlaue']  = df['Value'].apply(lambda x:x*2)

In [35]:
df

,Date,Category,Value,Product,Sales,Region,Salesfillna,value_new,NewVlaue
0,2023-01-01,A,28.0,Product1,754.0,East,754.000000,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.000000,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.000000,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.000000,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.000000,26,52.0
5,2023-01-06,B,54.0,Product3,192.0,West,192.000000,54,108.0
6,2023-01-07,A,16.0,Product1,936.0,East,936.000000,16,32.0
7,2023-01-08,C,89.0,Product1,488.0,West,488.000000,89,178.0
8,2023-01-09,C,37.0,Product3,772.0,West,772.000000,37,74.0
9,2023-01-10,A,22.0,Product2,834.0,West,834.000000,22,44.0
10,2023-01-11,B,7.0,Product1,842.0,North,842.000000,7,14.0
11,2023-01-12,B,60.0,Product2,NaN,West,557.130435,60,120.0
12,2023-01-13,A,70.0,Product3,628.0,South,628.000000,70,140.0
13,2023-01-14,A,69.0,Product1,423.0,East,423.000000,69,138.0
14,2023-01-15,A,47.0,Product2,893.0,West,893.000000,47,94.0
15,2023-01-16,C,NaN,Product1,895.0,North,895.000000,51,NaN
16,2023-01-17,C,93.0,Product2,511.0,South,511.000000,93,186.0
17,2023-01-18,C,NaN,Product1,108.0,West,108.000000,51,NaN
18,2023-01-19,A,31.0,Product2,578.0,West,578.000000,31,62.0
19,2023-01-20,A,59.0,Product1,736.0,East,736.000000,59,118.0
20,2023-01-21,C,82.0,Product3,606.0,South,606.000000,82,164.0
21,2023-01-22,C,37.0,Product2,992.0,South,992.000000,37,74.0
22,2023-01-23,B,62.0,Product3,942.0,North,942.000000,62,124.0
23,2023-01-24,C,92.0,Product2,342.0,West,342.000000,92,184.0
24,2023-01-25,A,24.0,Product2,458.0,East,458.000000,24,48.0
25,2023-01-26,C,95.0,Product1,584.0,West,584.000000,95,190.0
26,2023-01-27,C,71.0,Product2,619.0,North,619.000000,71,142.0
27,2023-01-28,C,56.0,Product2,224.0,North,224.000000,56,112.0
28,2023-01-29,B,NaN,Product3,617.0,North,617.000000,51,NaN
29,2023-01-30,C,51.0,Product2,737.0,South,737.000000,51,102.0
30,2023-01-31,B,50.0,Product3,735.0,West,735.000000,50,100.0
31,2023-02-01,A,17.0,Product2,189.0,West,189.000000,17,34.0
32,2023-02-02,B,63.0,Product3,338.0,South,338.000000,63,126.0
33,2023-02-03,C,27.0,Product3,NaN,East,557.130435,27,54.0
34,2023-02-04,C,70.0,Product3,669.0,West,669.000000,70,140.0
35,2023-02-05,B,60.0,Product2,NaN,West,557.130435,60,120.0
36,2023-02-06,C,36.0,Product3,177.0,East,177.000000,36,72.0
37,2023-02-07,C,2.0,Product1,NaN,North,557.130435,2,4.0
38,2023-02-08,C,94.0,Product1,408.0,South,408.000000,94,188.0
39,2023-02-09,A,62.0,Product1,155.0,West,155.000000,62,124.0
40,2023-02-10,B,15.0,Product1,578.0,East,578.000000,15,30.0
41,2023-02-11,C,97.0,Product1,256.0,East,256.000000,97,194.0
42,2023-02-12,A,93.0,Product3,164.0,West,164.000000,93,186.0
43,2023-02-13,A,43.0,Product3,949.0,East,949.000000,43,86.0
44,2023-02-14,A,96.0,Product3,830.0,East,830.000000,96,192.0
45,2023-02-15,B,99.0,Product2,599.0,West,599.000000,99,198.0
46,2023-02-16,B,6.0,Product1,938.0,South,938.000000,6,12.0
47,2023-02-17,B,69.0,Product3,143.0,West,143.000000,69,138.0
48,2023-02-18,C,65.0,Product3,182.0,North,182.000000,65,130.0
49,2023-02-19,C,11.0,Product3,708.0,North,708.000000,11,22.0

In [36]:
# data aggreagration and grouping ---suppose we want to know the total sales per category
df.groupby('Category')['Sales'].sum()

# we can also perform mean based on thr proeducts 
grouped_mean = df.groupby('Product')['Value'].mean()
# her product is the categorical value (means it has diff categorieas as product 1 pro 2etx)
# we do also need to find the mean to determine which category has the mosre sales

In [37]:
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [38]:
 # performing the grouped based on the two categorical product 
Gsum  = df.groupby(["Product" , "Region"])['Value'].sum()
print(Gsum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [39]:
# applying the multiple agrregreating Function 
Group_Agregration  = df.groupby('Product')['Value'].agg(['mean' , 'sum'])
Group_Agregration

               mean    sum
Product
Product1  46.214286  647.0
Product2  52.800000  792.0
Product3  55.166667  993.0

In [45]:
# merging and joing the dataframe  
df1 = pd.DataFrame( { 'key' : ['a' , 'b ' , 'c'], 'value 1 ' : [10 , 20 , 30 ] } )
df2 = pd.DataFrame( { 'key' : ['a' , 'b ' , 'c','d'], 'value 2 ' : [100 , 200 , 300,400 ] } )

df1

  key  value 1
0   a        10
1  b         20
2   c        30

In [46]:
# mergin the datafram based on th e key coluumns 
# the parameter to the merge are ----two fraes that we want to merge 
# ---- 2---- then the next we can take os " on" indicate which columst obe merged 
#--3-- tehn the 3rd indicateteh joint type  ---how = inner--

pd.merge(df1 , df2 , on = "key" , how = 'inner') # on which column we want to work and which way por which operation to perform

  key  value 1   value 2
0   a        10       100
1  b         20       200
2   c        30       300

In [47]:
pd.merge(df1 , df2 , on = "key" , how = 'outer') # on which column we want to work and which way por which operation to perform

  key  value 1   value 2
0   a      10.0       100
1  b       20.0       200
2   c      30.0       300
3   d       NaN       400